### ISSUE TITLE
Конструктор - Вопросы - Поле Вопрос имеет предзаполнение вместо плейсхолдера "Введите название вопроса" на макете(вообще так себе плйсхолдер лучше уж "Введите вопрос")

### ISSUE THREAD

**Issue by petrtopor** [petrtopor/quizzes-app#61]

**Comment by IgorAlikin63** [comment]
Думаю лучше изменить на плейсхолдер "Введите вопрос", предзаполнение плохая идея, начнут писать посреди текста существующего просто кликнув в случайную область поля
